### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/gendercoder#56]
(or new maintainer _team_)

If you're interested, please comment in the issue or email `info@ropensci.org`.

For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html);
- [Package Maintainer Cheatsheet](https://devdevguide.netlify.app/maintenance_cheatsheet.html);
- the blog post [What does it mean to maintain a package?](https://ropensci.org/blog/2023/02/07/what-does-it-mean-to-maintain-a-package/).

@ropensci/admin @ekothe @Lingtax

**Comment by maelle** [comment]
@YaoxiangLi volunteered! :tada:

@YaoxiangLi, please update the DESCRIPTION file, removing the "cre" role from the former maintainer.

**Comment by maelle** [comment]
@ekothe @Lingtax thanks so much for your work on this package :blue_heart:

**Comment by YaoxiangLi** [comment]
Thanks Maëlle, I have updated the DESCRIPTION file as suggested and will close this issue.

**Comment by maelle** [comment]
Thank you!!
